version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["poetry", "run", "flask", "run", "--host", "0.0.0.0"]
